@startuml

participant javascript
participant WebView
participant TdriveWebViewClient
participant WebViewInterface
participant SetPlayerChangeListenerFunction
participant TdriveApplication

TdriveApplication -> DingaPlayerManager : setChangeListener

javascript -> WebView : URL 설정:\n functionName,\n callId,\n parameter,\n callbackName

WebView -> TdriveWebViewClient : shouldOverrideUrlLoading(URL)

TdriveWebViewClient -> TdriveWebViewClient : parseWebViewInterfaceUrl

TdriveWebViewClient -> TdriveWebViewClient : invokeFunction

TdriveWebViewClient -> WebViewInterface : getFunction(functionName)

WebViewInterface -> TdriveWebViewClient : SetPlayerChangeListenerFunction 객체

TdriveWebViewClient -> SetPlayerChangeListenerFunction : call(SetPlayerChangeListenerFunctionContext)

SetPlayerChangeListenerFunction -> TdriveApplication : addPlayerListenerInfo

SetPlayerChangeListenerFunction -> WebView : evaluateJavascript, loadUrl:\n functionName,\n callId,\n parameter,\n callbackName

WebView -> javascript : result(SET_LISTENER)

... song change ...

DingaPlayerManager -> TdriveApplication : onSongChanged

TdriveApplication -> WebView : evaluateJavascript, loadUrl:\n functionName,\n callId,\n parameter,\n callbackName

WebView -> javascript : result(SONG_CHANGE)

... player state change ...

DingaPlayerManager -> TdriveApplication : onStateChanged

TdriveApplication -> WebView : evaluateJavascript, loadUrl:\n functionName,\n callId,\n parameter,\n callbackName

WebView -> javascript : result(STATE_CHANGE)

@enduml